export const data = [
  {
    id: 1,
    company: "Company A",
    delivery: "Delivery 1",
    items: 10,
    address: "123 Main St",
    order: "Order 1",
    amount: 500,
    status: "In Progress",
  },
  {
    id: 2,
    company: "Company A",
    delivery: "Delivery 2",
    items: 15,
    address: "123 Main St",
    order: "Order 1",
    amount: 700,
    status: "Delivered",
  },
  {
    id: 3,
    company: "Company B",
    delivery: "Delivery 3",
    items: 12,
    address: "456 Elm St",
    order: "Order 2",
    amount: 600,
    status: "In Progress",
  },
  {
    id: 4,
    company: "Company B",
    delivery: "Delivery 4",
    items: 8,
    address: "456 Elm St",
    order: "Order 2",
    amount: 400,
    status: "Delivered",
  },
  {
    id: 5,
    company: "Company C",
    delivery: "Delivery 5",
    items: 18,
    address: "789 Oak St",
    order: "Order 3",
    amount: 900,
    status: "In Progress",
  },
  {
    id: 6,
    company: "Company C",
    delivery: "Delivery 6",
    items: 20,
    address: "789 Oak St",
    order: "Order 3",
    amount: 1100,
    status: "Delivered",
  },
  {
    id: 7,
    company: "Company D",
    delivery: "Delivery 7",
    items: 9,
    address: "101 Elm St",
    order: "Order 4",
    amount: 550,
    status: "In Progress",
  },
  {
    id: 8,
    company: "Company D",
    delivery: "Delivery 8",
    items: 14,
    address: "101 Elm St",
    order: "Order 4",
    amount: 750,
    status: "Delivered",
  },
  {
    id: 9,
    company: "Company E",
    delivery: "Delivery 9",
    items: 11,
    address: "222 Main St",
    order: "Order 5",
    amount: 620,
    status: "In Progress",
  },
  {
    id: 10,
    company: "Company E",
    delivery: "Delivery 10",
    items: 16,
    address: "222 Main St",
    order: "Order 5",
    amount: 820,
    status: "Delivered",
  },
  {
    id: 11,
    company: "Company F",
    delivery: "Delivery 11",
    items: 13,
    address: "333 Oak St",
    order: "Order 6",
    amount: 690,
    status: "In Progress",
  },
  {
    id: 12,
    company: "Company F",
    delivery: "Delivery 12",
    items: 17,
    address: "333 Oak St",
    order: "Order 6",
    amount: 950,
    status: "Delivered",
  },
  {
    id: 13,
    company: "Company G",
    delivery: "Delivery 13",
    items: 8,
    address: "444 Elm St",
    order: "Order 7",
    amount: 450,
    status: "In Progress",
  },
  {
    id: 14,
    company: "Company G",
    delivery: "Delivery 14",
    items: 12,
    address: "444 Elm St",
    order: "Order 7",
    amount: 680,
    status: "Delivered",
  },
  {
    id: 15,
    company: "Company H",
    delivery: "Delivery 15",
    items: 15,
    address: "555 Main St",
    order: "Order 8",
    amount: 750,
    status: "In Progress",
  },
  {
    id: 16,
    company: "Company H",
    delivery: "Delivery 16",
    items: 19,
    address: "555 Main St",
    order: "Order 8",
    amount: 1050,
    status: "Delivered",
  },
  {
    id: 17,
    company: "Company I",
    delivery: "Delivery 17",
    items: 12,
    address: "666 Oak St",
    order: "Order 9",
    amount: 600,
    status: "In Progress",
  },
  {
    id: 18,
    company: "Company I",
    delivery: "Delivery 18",
    items: 16,
    address: "666 Oak St",
    order: "Order 9",
    amount: 900,
    status: "Delivered",
  },
  {
    id: 19,
    company: "Company J",
    delivery: "Delivery 19",
    items: 14,
    address: "777 Elm St",
    order: "Order 10",
    amount: 700,
    status: "In Progress",
  },
  {
    id: 20,
    company: "Company J",
    delivery: "Delivery 20",
    items: 18,
    address: "777 Elm St",
    order: "Order 10",
    amount: 950,
    status: "Delivered",
  },
];
