export const data = [
  {
    id: 1,
    company: "Company A",
    siteManager: "Manager 1",
    items: 45,
    address: "123 Main St",
    location: "New York",
    amount: 55000,
  },
  {
    id: 2,
    company: "Company B",
    siteManager: "Manager 2",
    items: 55,
    address: "456 Elm St",
    location: "California",
    amount: 60000,
  },
  {
    id: 3,
    company: "Company C",
    siteManager: "Manager 3",
    items: 38,
    address: "789 Oak St",
    location: "Texas",
    amount: 48000,
  },
  {
    id: 4,
    company: "Company D",
    siteManager: "Manager 4",
    items: 62,
    address: "101 Pine St",
    location: "Florida",
    amount: 72000,
  },
  {
    id: 5,
    company: "Company E",
    siteManager: "Manager 5",
    items: 29,
    address: "222 Cedar St",
    location: "Arizona",
    amount: 52000,
  },
  {
    id: 6,
    company: "Company F",
    siteManager: "Manager 6",
    items: 47,
    address: "333 Birch St",
    location: "Ohio",
    amount: 58000,
  },
  {
    id: 7,
    company: "Company G",
    siteManager: "Manager 7",
    items: 34,
    address: "444 Maple St",
    location: "Colorado",
    amount: 51000,
  },
  {
    id: 8,
    company: "Company H",
    siteManager: "Manager 8",
    items: 52,
    address: "555 Redwood St",
    location: "Nevada",
    amount: 59000,
  },
  {
    id: 9,
    company: "Company I",
    siteManager: "Manager 9",
    items: 41,
    address: "666 Willow St",
    location: "Illinois",
    amount: 62000,
  },
  {
    id: 10,
    company: "Company J",
    siteManager: "Manager 10",
    items: 58,
    address: "777 Cedar St",
    location: "New Jersey",
    amount: 68000,
  },
  {
    id: 11,
    company: "Company K",
    siteManager: "Manager 11",
    items: 36,
    address: "888 Elm St",
    location: "Michigan",
    amount: 54000,
  },
  {
    id: 12,
    company: "Company L",
    siteManager: "Manager 12",
    items: 43,
    address: "999 Oak St",
    location: "Georgia",
    amount: 59000,
  },
  {
    id: 13,
    company: "Company M",
    siteManager: "Manager 13",
    items: 49,
    address: "111 Birch St",
    location: "Wisconsin",
    amount: 61000,
  },
  {
    id: 14,
    company: "Company N",
    siteManager: "Manager 14",
    items: 30,
    address: "222 Maple St",
    location: "Virginia",
    amount: 53000,
  },
  {
    id: 15,
    company: "Company O",
    siteManager: "Manager 15",
    items: 51,
    address: "333 Pine St",
    location: "Oregon",
    amount: 59000,
  },
  {
    id: 16,
    company: "Company P",
    siteManager: "Manager 16",
    items: 42,
    address: "444 Redwood St",
    location: "Missouri",
    amount: 57000,
  },
  {
    id: 17,
    company: "Company Q",
    siteManager: "Manager 17",
    items: 37,
    address: "555 Cedar St",
    location: "Kentucky",
    amount: 55000,
  },
  {
    id: 18,
    company: "Company R",
    siteManager: "Manager 18",
    items: 46,
    address: "666 Elm St",
    location: "Washington",
    amount: 59000,
  },
  {
    id: 19,
    company: "Company S",
    siteManager: "Manager 19",
    items: 40,
    address: "777 Oak St",
    location: "Indiana",
    amount: 57000,
  },
  {
    id: 20,
    company: "Company T",
    siteManager: "Manager 20",
    items: 56,
    address: "888 Birch St",
    location: "North Carolina",
    amount: 63000,
  },
];
